const $=id=>document.getElementById(id);
const state={conversation:null,scene:'search',busy:false,lastResult:null,seenEvents:0};
const scenePrompt={search:'最近搜索“露营灯”的结果不太准，帮我复现问题并给一个改进方案，但先不要上线。',recommend:'帮我看看用户 u-lin 的推荐首屏，重点检查内容重复、新鲜度和有没有更好的候选方案。',compare:'帮我对比一个搜索和推荐的候选改进方案，先做离线复核，不要直接上线。',audit:'做一次全局体检，告诉我搜索和推荐里现在最值得先解决的三个问题。'};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function api(path,opt={}){const r=await fetch(path,{headers:{...(opt.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(opt.headers||{})},...opt});if(!r.ok){let t=await r.text();try{t=JSON.parse(t).detail||t}catch{}throw new Error(t||`HTTP ${r.status}`)}return r.json()}
function toast(t){const el=$('toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1900)}
function md(text){let s=esc(text||'');s=s.replace(/^###\s+(.+)$/gm,'<h3>$1</h3>');const lines=s.split('\n'),out=[];let list=false;for(const line of lines){if(line.startsWith('- ')){if(!list){out.push('<ul>');list=true}out.push(`<li>${line.slice(2)}</li>`)}else{if(list){out.push('</ul>');list=false}if(line.trim())out.push(`<p>${line}</p>`)}}if(list)out.push('</ul>');return out.join('')}
function autoSize(){const el=$('input');el.style.height='auto';el.style.height=Math.min(130,Math.max(44,el.scrollHeight))+'px'}
function scrollBottom(){requestAnimationFrame(()=>{$('scrollArea').scrollTop=$('scrollArea').scrollHeight})}
async function loadStatus(){const s=await api('/api/status');const d=s.data;$('dataName').textContent=d.name;$('dataMeta').textContent=`${d.items} 内容 · ${d.users} 用户`;$('datasetTitle').textContent=d.name;$('dataGrid').innerHTML=[['内容',d.items],['用户',d.users],['行为',d.interactions],['已复核问题',d.queries]].map(([k,v])=>`<div class="data-cell"><b>${v}</b><span>${k}</span></div>`).join('')}
async function loadHistory(){const rows=await api('/api/conversations');$('historyList').innerHTML=rows.length?rows.map(x=>`<div class="history-item" data-id="${x.id}"><b>${esc(x.title)}</b><small>${new Date(x.updated_at*1000).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}</small></div>`).join(''):'<div class="empty">还没有历史任务。</div>';document.querySelectorAll('.history-item').forEach(x=>x.onclick=()=>openConversation(x.dataset.id))}
async function newConversation(scene=state.scene){const c=await api('/api/conversations',{method:'POST',body:JSON.stringify({scene,title:'新的体验任务'})});state.conversation=c;state.lastResult=null;renderMessages([]);$('taskTitle').textContent=c.title;$('input').value=scenePrompt[scene]||'';autoSize();await loadHistory();$('input').focus()}
async function openConversation(id){const c=await api(`/api/conversations/${id}`);state.conversation=c;state.lastResult=[...c.messages].reverse().find(x=>x.role==='assistant')?.payload||null;$('taskTitle').textContent=c.title;renderMessages(c.messages);if(state.lastResult)renderResult(state.lastResult);await loadHistory()}
function renderMessages(rows){$('welcome').hidden=rows.length>0;$('messageList').innerHTML=rows.map(m=>m.role==='user'?`<div class="msg user"><div class="bubble">${esc(m.content)}</div></div>`:`<div class="msg assistant"><div class="bubble"><div class="assistant-label"><b>灵境</b><span>已完成本次执行</span></div><div class="answer">${md(m.content)}</div></div></div>`).join('');scrollBottom()}
function appendUser(text){$('welcome').hidden=true;$('messageList').insertAdjacentHTML('beforeend',`<div class="msg user"><div class="bubble">${esc(text)}</div></div>`);scrollBottom()}
function appendAssistant(msg){$('messageList').insertAdjacentHTML('beforeend',`<div class="msg assistant"><div class="bubble"><div class="assistant-label"><b>灵境</b><span>已完成本次执行</span></div><div class="answer">${md(msg.content)}</div></div></div>`);scrollBottom()}
function renderEvent(ev,index){const done=ev.progress>=100||index<state.seenEvents-1;return `<div class="timeline-row ${done?'done':''}"><span>${done?'✓':String(index+1).padStart(2,'0')}</span><div><b>${esc(ev.title)}</b><small>${esc(ev.detail)}</small></div></div>`}
function renderRunning(events=[]){if(!events.length)return;const ev=events.at(-1);$('running').hidden=false;$('runTitle').textContent=ev.title;$('runDetail').textContent=ev.detail;$('runPercent').textContent=`${ev.progress}%`;$('runBar').style.width=`${ev.progress}%`;$('stateText').textContent=ev.progress>=100?'已完成':'正在执行';$('timeline').innerHTML=events.map(renderEvent).join('');state.seenEvents=events.length;scrollBottom()}
function renderResult(r){state.lastResult=r;$('running').hidden=true;$('stateText').textContent='已完成';$('timeline').innerHTML=(r.events||[]).map((ev,i)=>renderEvent({...ev,progress:100},i)).join('')||'<div class="empty">本次没有执行记录。</div>';$('evidenceList').innerHTML=(r.evidence||[]).length?(r.evidence||[]).map((x,i)=>`<div class="evidence-item"><span>依据 ${String(i+1).padStart(2,'0')}</span><b>${esc(x.title)}</b><small>${esc(x.detail||'已在本次执行中复核')}</small></div>`).join(''):'<div class="empty">本次没有生成具体结果证据。</div>';$('suggestions').innerHTML=(r.suggestions||[]).map(x=>`<button>${esc(x)}</button>`).join('');$('suggestions').querySelectorAll('button').forEach(b=>b.onclick=()=>{$('input').value=b.textContent;autoSize();$('input').focus()})}
async function pollRun(id){for(let i=0;i<160;i++){const r=await api(`/api/runs/${id}`);renderRunning(r.events||[]);if(r.status==='completed'){state.busy=false;$('sendBtn').disabled=false;appendAssistant(r.message);renderResult(r.result);await loadHistory();return}if(r.status==='failed'){state.busy=false;$('sendBtn').disabled=false;$('running').hidden=true;toast('执行失败：'+(r.error||'未知错误'));return}await new Promise(res=>setTimeout(res,140))}state.busy=false;$('sendBtn').disabled=false;toast('执行超时，请重试')}
async function send(){if(state.busy)return;const text=$('input').value.trim();if(!text)return;if(!state.conversation)await newConversation(state.scene);state.busy=true;$('sendBtn').disabled=true;appendUser(text);$('input').value='';autoSize();$('stateText').textContent='正在执行';$('timeline').innerHTML='<div class="empty">正在建立本次执行上下文…</div>';$('running').hidden=false;try{const res=await api(`/api/conversations/${state.conversation.id}/messages`,{method:'POST',body:JSON.stringify({content:text})});pollRun(res.run_id)}catch(e){state.busy=false;$('sendBtn').disabled=false;$('running').hidden=true;toast(e.message)}}
async function importFile(file){const fd=new FormData();fd.append('file',file);try{const r=await api('/api/data/import-file',{method:'POST',body:fd});toast(`已导入 ${r.data.items} 条内容`);await loadStatus();await newConversation('audit')}catch(e){toast(e.message)}}
function bind(){document.querySelectorAll('.scene').forEach(b=>b.onclick=()=>{state.scene=b.dataset.scene;document.querySelectorAll('.scene').forEach(x=>x.classList.toggle('active',x===b));$('input').value=scenePrompt[state.scene];autoSize();$('input').focus()});document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{$('input').value=b.dataset.prompt;autoSize();$('input').focus()});document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));$(`panel-${b.dataset.tab}`).classList.add('active')});$('newTaskBtn').onclick=()=>newConversation(state.scene);$('refreshBtn').onclick=loadHistory;$('sendBtn').onclick=send;$('input').oninput=autoSize;$('input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};$('importBtn').onclick=$('importBtnSide').onclick=()=>$('fileInput').click();$('fileInput').onchange=e=>{if(e.target.files[0])importFile(e.target.files[0]);e.target.value=''};$('copyBtn').onclick=async()=>{if(!state.lastResult)return toast('还没有可复制的结论');await navigator.clipboard?.writeText(state.lastResult.answer||'');toast('结论已复制')}}
async function boot(){bind();autoSize();await loadStatus();await loadHistory();const rows=await api('/api/conversations');if(rows.length)await openConversation(rows[0].id);else await newConversation('search')}
boot().catch(e=>toast(e.message));
